SRC/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Books Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/classes/BookPlanner.cls
global class BookPlanner{
    global class BookPlan{
        webservice String bookName;
        webservice Decimal price;
        webservice String author;
        webservice String bookId;
    }
        
    webservice static BookPlan CreateBook(BookPlan plan){
        Book__c book = new Book__c();
        book.Name = plan.bookName;
        book.Price__c = plan.price;
        book.Author__c = plan.author;
        insert book;
        return plan;
        }
    }